version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "3000:3000"

  cadvisor:
    image: google/cadvisor:latest
    networks:
      - monitoring_net
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "9323:9323"

networks:
  monitoring_net:
    driver: overlay

volumes:
  prometheus_data:
  grafana_data:
